services:

  web:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      target: development
    command: python manage.py runserver 0.0.0.0:5011
    restart: on-failure
    env_file:
      - ./.env.dev
#    command: ls -la /app
    ports:
      - "5011:5011"
    volumes:
      - ../app/:/app/
    depends_on:
      - db

  db:
    image: "postgres:12-alpine"
    restart: unless-stopped
    env_file:
      - ./.env.dev
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
